create table
  public.characters (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    level integer null default 0,
    health integer null default 100,
    gold integer null default 0,
    inventory_size integer null default 10,
    user_id bigint null,
    quest_id bigint null,
    constraint Characters_pkey primary key (id),
    constraint Characters_id_key unique (id),
    constraint Characters_QuestID_fkey foreign key (quest_id) references quests (id),
    constraint Characters_UserID_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.game_log (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    error_id bigint null,
    char_id integer null,
    description text null,
    constraint GameLog_pkey primary key (id),
    constraint GameLog_CharID_fkey foreign key (char_id) references characters (id)
  ) tablespace pg_default;

create table
  public.inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    equipped boolean null default false,
    equip_slot integer null,
    quantity integer null,
    char_id bigint not null,
    item_id bigint not null,
    constraint Inventory_pkey primary key (id),
    constraint Inventory_CharID_fkey foreign key (char_id) references characters (id),
    constraint Inventory_ItemID_fkey foreign key (item_id) references items (id)
  ) tablespace pg_default;

create table
  public.items (
    id bigint generated by default as identity,
    name text null,
    description text null,
    type text null,
    level integer null,
    sell_price integer null,
    constraint Items_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.quests (
    id bigint generated by default as identity,
    name text null,
    description text null,
    level integer null,
    gold integer null,
    item_id integer null,
    constraint Quests_pkey primary key (id),
    constraint Quests_ItemID_fkey foreign key (item_id) references items (id)
  ) tablespace pg_default;

create table
  public.shops (
    id bigint generated by default as identity,
    name text null,
    description text null,
    level integer null,
    gold integer null,
    constraint Shops_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.stock (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    price integer null,
    quantity integer null,
    shop_id integer not null,
    item_id integer not null,
    constraint Stock_pkey primary key (id),
    constraint Stock_ItemID_fkey foreign key (item_id) references items (id),
    constraint Stock_ShopID_fkey foreign key (shop_id) references shops (id)
  ) tablespace pg_default;

create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text not null,
    password text not null,
    constraint Users_pkey primary key (id),
    constraint Users_Username_key unique (username),
    constraint Users_id_key unique (id)
  ) tablespace pg_default;
